from __future__ import annotations

import json
import re
from pathlib import Path
from pprint import pformat
from typing import Any


class TraceCodegenError(ValueError):
    pass


_INFRASTRUCTURE_EVENTS = {"rpc", "trace.start", "trace.stop"}


def load_trace_events(path: str | Path) -> list[dict[str, Any]]:
    trace_path = Path(path).expanduser().resolve()
    try:
        raw = json.loads(trace_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise TraceCodegenError(f"Trace JSON is invalid: {trace_path}: {exc}") from exc
    return normalize_trace_events(raw)


def normalize_trace_events(trace: Any) -> list[dict[str, Any]]:
    if isinstance(trace, list):
        raw_events = trace
    elif isinstance(trace, dict) and isinstance(trace.get("events"), list):
        raw_events = trace["events"]
    else:
        raise TraceCodegenError("Trace input must be a JSON event array or an object with an events array")

    events: list[dict[str, Any]] = []
    for index, raw_event in enumerate(raw_events):
        if not isinstance(raw_event, dict):
            raise TraceCodegenError(f"Trace event {index} must be an object")
        event_type = raw_event.get("type")
        if not event_type:
            raise TraceCodegenError(f"Trace event {index} is missing type")
        data = raw_event.get("data", {})
        if data is None:
            data = {}
        if not isinstance(data, dict):
            raise TraceCodegenError(f"Trace event {index} data must be an object")
        events.append(dict(raw_event, type=str(event_type), data=data))
    return events


def generate_test_from_trace(
    trace: Any,
    *,
    test_name: str = "test_generated_trace",
    include_header: bool = True,
) -> str:
    events = normalize_trace_events(trace)
    function_name = _safe_test_name(test_name)
    body: list[str] = [
        "# Generated by godot-playwright codegen-trace.",
        "# Review selectors and add assertions before committing.",
    ]

    index = 0
    generated_count = 0
    unsupported_count = 0
    while index < len(events):
        event = events[index]
        lines, consumed = _event_lines(events, index)
        if lines:
            body.extend(lines)
            if not all(line.lstrip().startswith("#") for line in lines):
                generated_count += 1
            else:
                unsupported_count += 1
        index += max(consumed, 1)

    if generated_count == 0 and unsupported_count == 0:
        body.append("pass")

    lines: list[str] = []
    if include_header:
        lines.extend(["from __future__ import annotations", "", ""])
    lines.append(f"def {function_name}(godot):")
    lines.extend(f"    {line}" for line in body)
    lines.append("")
    return "\n".join(lines)


def _event_lines(events: list[dict[str, Any]], index: int) -> tuple[list[str], int]:
    event = events[index]
    event_type = str(event.get("type", ""))
    data = _event_data(event)
    if event_type in _INFRASTRUCTURE_EVENTS:
        return [], 1

    if event_type == "input.key":
        paired = _paired_key_press(events, index)
        if paired is not None:
            return [paired], 2

    line = _single_event_line(event_type, data)
    if line is None:
        return [_unsupported_comment(event_type, data)], 1
    return [line], 1


def _single_event_line(event_type: str, data: dict[str, Any]) -> str | None:
    if event_type == "protocol.describe":
        kwargs = []
        for name, default in (
            ("include_methods", True),
            ("include_domains", True),
            ("include_features", True),
        ):
            if data.get(name, default) != default:
                kwargs.append((name, data.get(name)))
        return _call("godot.protocol_describe", [], kwargs)
    if event_type == "node.click":
        return f"{_locator(data)}.click()"
    if event_type == "node.focus":
        return f"{_locator(data)}.focus()"
    if event_type == "node.fill":
        return f"{_locator(data)}.fill({_py(data.get('text', ''))})"
    if event_type == "node.accept_dialog":
        return f"{_locator(data)}.accept_dialog()"
    if event_type == "node.dismiss_dialog":
        return f"{_locator(data)}.dismiss_dialog()"
    if event_type == "node.set_value":
        return f"{_locator(data)}.set_value({_py(data.get('value'))})"
    if event_type == "node.set_checked":
        checked = bool(data.get("checked"))
        method = "check" if checked else "uncheck"
        return f"{_locator(data)}.{method}()"
    if event_type == "node.select_option":
        return f"{_locator(data)}.select_option({_py(_select_option_arg(data))})"
    if event_type == "node.select_tab":
        return f"{_locator(data)}.select_tab({_py(_select_tab_arg(data))})"
    if event_type == "node.select_menu_item":
        checked = _selected_item_checked(data)
        suffix = "" if checked is None else f", checked={_py(checked)}"
        return f"{_locator(data)}.select_menu_item({_py(_select_item_arg(data))}{suffix})"
    if event_type == "node.select_item":
        return f"{_locator(data)}.select_item({_py(_select_list_arg(data))})"
    if event_type == "node.select_tree_item":
        return f"{_locator(data)}.select_tree_item({_py(_select_tree_arg(data))})"
    if event_type == "node.set_property":
        return f"{_locator(data)}.set({_py(data.get('property', ''))}, {_py(data.get('value'))})"
    if event_type == "node.set_properties":
        if "values" not in data:
            return _unsupported_comment(event_type, data, detail="trace omits property values")
        return _call("godot.set_node_properties", [_node_selector(data), data.get("values", {})], _undo_kwargs(data))
    if event_type == "node.set_all_properties":
        if "values" not in data:
            return _unsupported_comment(event_type, data, detail="trace omits property values")
        kwargs = _undo_kwargs(data)
        if data.get("limit", 0) != 0:
            kwargs.append(("limit", data.get("limit")))
        return f"{_locator_for_selector(data.get('selector', {}), data.get('root'))}.set_all_properties({_py(data.get('values', {}))}{_kwargs_suffix(kwargs)})"
    if event_type == "node.attach_script":
        kwargs = []
        if data.get("inspect") is True:
            kwargs.append(("inspect", True))
        if data.get("reload") is False:
            kwargs.append(("reload", False))
        return _call("godot.attach_script", [_node_selector(data), data.get("script", data.get("script_path", ""))], kwargs)
    if event_type == "node.detach_script":
        kwargs = []
        if data.get("inspect") is True:
            kwargs.append(("inspect", True))
        return _call("godot.detach_script", [_node_selector(data)], kwargs)
    if event_type == "node.create_tree":
        kwargs = [("parent", data.get("parent", "edited"))]
        if data.get("owner_scene") is False:
            kwargs.append(("owner_scene", False))
        if data.get("persistent_groups") is False:
            kwargs.append(("persistent_groups", False))
        if data.get("reload_scripts") is False:
            kwargs.append(("reload_scripts", False))
        if data.get("max_nodes", 100) != 100:
            kwargs.append(("max_nodes", data.get("max_nodes")))
        return _call("godot.create_node_tree", [data.get("nodes", [])], kwargs)
    if event_type == "node.create":
        kwargs = []
        if data.get("name") and data.get("name") != data.get("class", "Node"):
            kwargs.append(("name", data.get("name")))
        if data.get("owner_scene") is False:
            kwargs.append(("owner_scene", False))
        kwargs.extend(_undo_kwargs(data))
        return _call("godot.create_node", [data.get("parent", "edited"), data.get("class", data.get("type", "Node"))], kwargs)
    if event_type == "node.instantiate_scene":
        kwargs = [("parent", data.get("parent", "edited"))]
        if data.get("name"):
            kwargs.append(("name", data.get("name")))
        if data.get("index") is not None:
            kwargs.append(("index", data.get("index")))
        if data.get("owner_scene") is False:
            kwargs.append(("owner_scene", False))
        return _call("godot.instantiate_scene", [data.get("source_scene", data.get("scene", data.get("path", "")))], kwargs)
    if event_type == "node.save_as_scene":
        kwargs = []
        if data.get("overwrite") is False:
            kwargs.append(("overwrite", False))
        return _call("godot.save_node_as_scene", [data.get("source", data.get("selector", "")), data.get("path", "")], kwargs)
    if event_type == "node.set_metadata":
        if "values" not in data:
            return _unsupported_comment(event_type, data, detail="trace omits metadata values")
        return _call("godot.set_node_metadata", [_node_selector(data), data.get("values", {})], _undo_kwargs(data))
    if event_type == "node.remove_metadata":
        return _call("godot.remove_node_metadata", [_node_selector(data), data.get("names", data.get("name", []))], _undo_kwargs(data))
    if event_type == "node.add_group":
        kwargs = []
        if data.get("persistent") is False:
            kwargs.append(("persistent", False))
        return _call("godot.add_node_group", [_node_selector(data), data.get("group", "")], kwargs)
    if event_type == "node.remove_group":
        return _call("godot.remove_node_group", [_node_selector(data), data.get("group", "")])
    if event_type == "node.reparent":
        kwargs = []
        if data.get("index") is not None:
            kwargs.append(("index", data.get("index")))
        if data.get("keep_global_transform") is False:
            kwargs.append(("keep_global_transform", False))
        if data.get("owner_scene") is False:
            kwargs.append(("owner_scene", False))
        return _call("godot.reparent_node", [data.get("old_path", data.get("path", data.get("selector", ""))), data.get("new_parent", data.get("parent", ""))], kwargs)
    if event_type == "node.move":
        return _call("godot.move_node", [_node_selector(data), data.get("index", 0)])
    if event_type == "node.duplicate":
        kwargs = []
        if data.get("parent") is not None:
            kwargs.append(("parent", data.get("parent")))
        if data.get("name"):
            kwargs.append(("name", data.get("name")))
        if data.get("index") is not None:
            kwargs.append(("index", data.get("index")))
        if data.get("flags") is not None:
            kwargs.append(("flags", data.get("flags")))
        if data.get("owner_scene") is False:
            kwargs.append(("owner_scene", False))
        return _call("godot.duplicate_node", [data.get("source", data.get("selector", ""))], kwargs)
    if event_type == "node.delete":
        return _call("godot.delete_node", [_node_selector(data)])
    if event_type == "node.evaluate":
        return f"{_locator(data)}.evaluate({_py(data.get('expression', ''))})"
    if event_type == "node.evaluate_all":
        root = data.get("root")
        root_arg = "" if root in (None, "", "edited") else f", root={_py(root)}"
        return f"godot.locator({_py(data.get('selector', {}))}{root_arg}).evaluate_all({_py(data.get('expression', ''))})"
    if event_type == "node.call_all":
        method = data.get("method", "")
        if not method:
            return _unsupported_comment(event_type, data, detail="trace omits method")
        kwargs = []
        if data.get("limit", 0) != 0:
            kwargs.append(("limit", data.get("limit")))
        if data.get("strict") is False:
            kwargs.append(("strict", False))
        return _call(f"{_locator_for_selector(data.get('selector', {}), data.get('root'))}.call_all", [method], kwargs)
    if event_type == "node.classes":
        kwargs = []
        for name, default in (
            ("base_class", "Node"),
            ("name_contains", ""),
            ("max_results", 200),
        ):
            if data.get(name, default) != default:
                kwargs.append((name, data.get(name)))
        if data.get("include_abstract") is True:
            kwargs.append(("include_abstract", True))
        if data.get("include_disabled") is True:
            kwargs.append(("include_disabled", True))
        if data.get("include_property_counts") is False:
            kwargs.append(("include_property_counts", False))
        return _call("godot.node_classes", [], kwargs)
    if event_type == "node.class.describe":
        kwargs = []
        if data.get("storage_only") is True:
            kwargs.append(("storage_only", True))
        if data.get("include_internal") is True:
            kwargs.append(("include_internal", True))
        if data.get("include_values") is False:
            kwargs.append(("include_values", False))
        if data.get("include_methods") is False:
            kwargs.append(("include_methods", False))
        if data.get("include_signals") is False:
            kwargs.append(("include_signals", False))
        if data.get("properties"):
            kwargs.append(("properties", data.get("properties")))
        if data.get("methods"):
            kwargs.append(("methods", data.get("methods")))
        if data.get("signals"):
            kwargs.append(("signals", data.get("signals")))
        if data.get("name_contains", ""):
            kwargs.append(("name_contains", data.get("name_contains")))
        if data.get("method_contains", ""):
            kwargs.append(("method_contains", data.get("method_contains")))
        if data.get("signal_contains", ""):
            kwargs.append(("signal_contains", data.get("signal_contains")))
        if data.get("max_methods", 200) != 200:
            kwargs.append(("max_methods", data.get("max_methods")))
        if data.get("max_signals", 200) != 200:
            kwargs.append(("max_signals", data.get("max_signals")))
        return _call("godot.node_class_describe", [data.get("class", "Node")], kwargs)
    if event_type == "runtime.evaluate":
        root = data.get("root")
        root_arg = "" if root in (None, "", "edited") else f", root={_py(root)}"
        return f"godot.evaluate({_py(data.get('expression', ''))}{root_arg})"
    if event_type == "runtime.pause":
        return "godot.pause()"
    if event_type == "runtime.resume":
        return "godot.resume()"
    if event_type == "runtime.step_frames":
        kwargs = []
        if data.get("physics") is True:
            kwargs.append(("physics", True))
        return _call("godot.step_frames", [data.get("frames", 1)], kwargs)
    if event_type == "runtime.sample_frames":
        return "godot.sample_frames(1)"
    if event_type == "animation.play":
        kwargs = []
        if data.get("custom_blend", data.get("blend", -1.0)) != -1.0:
            kwargs.append(("blend", data.get("custom_blend", data.get("blend"))))
        if data.get("custom_speed", data.get("speed", 1.0)) != 1.0:
            kwargs.append(("speed", data.get("custom_speed", data.get("speed"))))
        if data.get("from_end") is True:
            kwargs.append(("from_end", True))
        return _call("godot.animation_play", [data.get("path", data.get("selector", "")), data.get("animation", "")], kwargs)
    if event_type == "animation.stop":
        kwargs = []
        if data.get("keep_state") is True:
            kwargs.append(("keep_state", True))
        return _call("godot.animation_stop", [data.get("path", data.get("selector", ""))], kwargs)
    if event_type == "animation.pause":
        return _call("godot.animation_pause", [data.get("path", data.get("selector", ""))])
    if event_type == "animation.seek":
        kwargs = []
        if data.get("update") is False:
            kwargs.append(("update", False))
        if data.get("update_only") is True:
            kwargs.append(("update_only", True))
        return _call("godot.animation_seek", [data.get("path", data.get("selector", "")), data.get("position", 0.0)], kwargs)
    if event_type == "animation.advance":
        kwargs = []
        if data.get("update") is False:
            kwargs.append(("update", False))
        if data.get("update_only") is True:
            kwargs.append(("update_only", True))
        return _call("godot.animation_advance", [data.get("path", data.get("selector", "")), data.get("delta", 0.0)], kwargs)
    if event_type == "physics2d.point":
        x, y = _vector2_components(data.get("position", data), fallback_x=data.get("x", 0.0), fallback_y=data.get("y", 0.0))
        return _call("godot.physics2d_point", [x, y], _physics_query_kwargs(data, dimensions=2, include_max_results=True))
    if event_type == "physics2d.ray":
        from_x, from_y = _vector2_components(data.get("from", {}), fallback_x=data.get("from_x", 0.0), fallback_y=data.get("from_y", 0.0))
        to_x, to_y = _vector2_components(data.get("to", {}), fallback_x=data.get("to_x", 0.0), fallback_y=data.get("to_y", 0.0))
        return _call("godot.physics2d_ray", [from_x, from_y, to_x, to_y], _physics_query_kwargs(data, dimensions=2))
    if event_type == "physics3d.point":
        x, y, z = _vector3_components(
            data.get("position", data),
            fallback_x=data.get("x", 0.0),
            fallback_y=data.get("y", 0.0),
            fallback_z=data.get("z", 0.0),
        )
        return _call("godot.physics3d_point", [x, y, z], _physics_query_kwargs(data, dimensions=3, include_max_results=True))
    if event_type == "physics3d.ray":
        from_x, from_y, from_z = _vector3_components(
            data.get("from", {}),
            fallback_x=data.get("from_x", 0.0),
            fallback_y=data.get("from_y", 0.0),
            fallback_z=data.get("from_z", 0.0),
        )
        to_x, to_y, to_z = _vector3_components(
            data.get("to", {}),
            fallback_x=data.get("to_x", 0.0),
            fallback_y=data.get("to_y", 0.0),
            fallback_z=data.get("to_z", 0.0),
        )
        return _call("godot.physics3d_ray", [from_x, from_y, from_z, to_x, to_y, to_z], _physics_query_kwargs(data, dimensions=3))
    if event_type == "audio.bus.info":
        kwargs: list[tuple[str, Any]] = []
        if "bus_name" in data:
            kwargs.append(("bus_name", data["bus_name"]))
        if "bus_index" in data:
            kwargs.append(("bus_index", data["bus_index"]))
        return _call("godot.audio_bus_info", [], kwargs)
    if event_type == "navigation.query_path":
        start = data.get("start", [0.0, 0.0, 0.0])
        target = data.get("target", [0.0, 0.0, 0.0])
        dimension = int(data.get("dimension", 3))
        kwargs = [("dimension", dimension)]
        return _call(
            "godot.navigation_query_path",
            [list(start), list(target)],
            kwargs,
        )
    if event_type == "camera3d.ray":
        x, y = _vector2_components(data.get("screen_position", data), fallback_x=data.get("x", 0.0), fallback_y=data.get("y", 0.0))
        return _call("godot.camera3d_ray", [x, y], _camera3d_kwargs(data))
    if event_type == "camera3d.pick":
        x, y = _vector2_components(data.get("screen_position", data), fallback_x=data.get("x", 0.0), fallback_y=data.get("y", 0.0))
        kwargs = _camera3d_kwargs(data)
        kwargs.extend(_physics_query_kwargs(data, dimensions=3))
        return _call("godot.camera3d_pick", [x, y], kwargs)
    if event_type == "scene.files":
        kwargs = []
        for name, default in (
            ("path", "res://"),
            ("name", ""),
            ("name_contains", ""),
            ("root_name", ""),
            ("root_class", ""),
            ("max_results", 200),
        ):
            if data.get(name, default) != default:
                kwargs.append((name, data.get(name)))
        if data.get("extensions") not in (None, ["tscn", "scn"]):
            kwargs.append(("extensions", data.get("extensions")))
        if data.get("include_dependencies") is False:
            kwargs.append(("include_dependencies", False))
        if data.get("include_nodes") is True:
            kwargs.append(("include_nodes", True))
        if data.get("recursive") is False:
            kwargs.append(("recursive", False))
        if data.get("include_hidden") is True:
            kwargs.append(("include_hidden", True))
        if data.get("max_scan_results") is not None:
            kwargs.append(("max_scan_results", data.get("max_scan_results")))
        return _call("godot.scene_files", [], kwargs)
    if event_type == "scene.file.describe":
        kwargs = []
        if data.get("include_nodes") is False:
            kwargs.append(("include_nodes", False))
        if data.get("include_properties") is True:
            kwargs.append(("include_properties", True))
        if data.get("include_resources") is False:
            kwargs.append(("include_resources", False))
        if data.get("include_connections") is False:
            kwargs.append(("include_connections", False))
        if data.get("include_dependencies") is False:
            kwargs.append(("include_dependencies", False))
        if data.get("include_source") is True:
            kwargs.append(("include_source", True))
        return _call("godot.scene_file_describe", [data.get("path", "")], kwargs)
    if event_type == "scene.change":
        if data.get("mode") == "editor_open":
            return f"godot.editor_open_scene({_py(data.get('path', ''))})"
        return f"godot.change_scene({_py(data.get('path', ''))})"
    if event_type == "scene.reload":
        return "godot.reload_scene()"
    if event_type == "scene.new":
        kwargs = []
        if data.get("class", "Node2D") != "Node2D":
            kwargs.append(("class_name", data.get("class")))
        if data.get("name", "Main") != "Main":
            kwargs.append(("name", data.get("name")))
        if data.get("close_existing", True) is False:
            kwargs.append(("close_existing", False))
        return _call("godot.editor_new_scene", [], kwargs)
    if event_type == "scene.open":
        return f"godot.editor_open_scene({_py(data.get('path', ''))})"
    if event_type == "scene.save":
        path = data.get("path", "")
        return _call("godot.editor_save_scene", [] if path == "" else [path])
    if event_type == "editor.play":
        scene = data.get("scene", "current")
        return _call("godot.editor_play", [] if scene == "current" else [scene])
    if event_type == "editor.stop":
        return "godot.editor_stop()"
    if event_type == "editor.ui.switch_main_screen":
        return _call("godot.editor_switch_main_screen", [data.get("name", data.get("screen", ""))])
    if event_type == "editor.ui.hide_bottom_panel":
        return "godot.editor_hide_bottom_panel()"
    if event_type == "editor.undo":
        return _call("godot.editor_undo", _optional_selector_args(data), _editor_history_kwargs(data))
    if event_type == "editor.redo":
        return _call("godot.editor_redo", _optional_selector_args(data), _editor_history_kwargs(data))
    if event_type == "editor.selection.set":
        selectors = _editor_selection_selectors(data)
        kwargs = _root_kwargs(data)
        if data.get("inspect") is True:
            kwargs.append(("inspect", True))
        if data.get("property"):
            kwargs.append(("property", data.get("property")))
        if data.get("inspector_only") is True:
            kwargs.append(("inspector_only", True))
        return _call("godot.editor_select", [selectors], kwargs)
    if event_type == "editor.inspect":
        args, kwargs = _editor_target_call(data)
        if data.get("property"):
            kwargs.append(("property", data.get("property")))
        if data.get("inspector_only") is True:
            kwargs.append(("inspector_only", True))
        return _call("godot.editor_inspect", args, kwargs)
    if event_type == "editor.inspector.set_property":
        if "value" not in data:
            return _unsupported_comment(event_type, data, detail="trace omits property value")
        args, kwargs = _editor_target_call(data)
        call_args = [data.get("property", ""), data.get("value")]
        call_args.extend(args)
        kwargs.extend(_editor_inspector_mutation_kwargs(data))
        return _call("godot.editor_inspector_set_property", call_args, kwargs)
    if event_type == "editor.inspector.set_properties":
        if "values" not in data:
            return _unsupported_comment(event_type, data, detail="trace omits property values")
        args, kwargs = _editor_target_call(data)
        call_args = [data.get("values", {})]
        call_args.extend(args)
        kwargs.extend(_editor_inspector_mutation_kwargs(data))
        return _call("godot.editor_inspector_set_properties", call_args, kwargs)
    if event_type == "editor.script.open":
        kwargs = []
        if data.get("line", -1) != -1:
            kwargs.append(("line", data.get("line")))
        if data.get("column", 0) != 0:
            kwargs.append(("column", data.get("column")))
        if data.get("grab_focus", True) is False:
            kwargs.append(("grab_focus", False))
        if data.get("force") is True:
            kwargs.append(("force", True))
        if data.get("restore_external_editor") is True:
            kwargs.append(("restore_external_editor", True))
        return _call("godot.editor_open_script", [data.get("path", "")], kwargs)
    if event_type == "script.file.describe":
        kwargs = []
        if data.get("include_source") is True:
            kwargs.append(("include_source", True))
        return _call("godot.script_file_describe", [data.get("path", "")], kwargs)
    if event_type == "script.classes":
        kwargs = []
        for name, default in (
            ("path", "res://"),
            ("class_name", ""),
            ("name_contains", ""),
            ("extends", ""),
            ("base_class", ""),
            ("max_results", 200),
        ):
            if data.get(name, default) != default:
                kwargs.append((name, data.get(name)))
        if data.get("include_anonymous") is True:
            kwargs.append(("include_anonymous", True))
        if data.get("recursive") is False:
            kwargs.append(("recursive", False))
        if data.get("include_hidden") is True:
            kwargs.append(("include_hidden", True))
        if data.get("max_scan_results") is not None:
            kwargs.append(("max_scan_results", data.get("max_scan_results")))
        return _call("godot.script_classes", [], kwargs)
    if event_type == "editor.filesystem.scan":
        paths = data.get("paths", [])
        if not paths:
            return "godot.editor_scan_filesystem()"
        if isinstance(paths, list) and len(paths) == 1:
            return _call("godot.editor_scan_filesystem", [paths[0]])
        return _call("godot.editor_scan_filesystem", [paths])
    if event_type == "editor.filesystem.select":
        kwargs = []
        if data.get("inspect") is True:
            kwargs.append(("inspect", True))
        return _call("godot.editor_filesystem_select", [data.get("path", "")], kwargs)
    if event_type == "editor.filesystem.open":
        kwargs = []
        if data.get("mode", "auto") != "auto":
            kwargs.append(("mode", data.get("mode")))
        if data.get("line", -1) != -1:
            kwargs.append(("line", data.get("line")))
        if data.get("column", 0) != 0:
            kwargs.append(("column", data.get("column")))
        if data.get("grab_focus", True) is False:
            kwargs.append(("grab_focus", False))
        if data.get("force") is True:
            kwargs.append(("force", True))
        if data.get("restore_external_editor") is True:
            kwargs.append(("restore_external_editor", True))
        if data.get("property"):
            kwargs.append(("property", data.get("property")))
        if data.get("inspector_only") is True:
            kwargs.append(("inspector_only", True))
        return _call("godot.editor_filesystem_open", [data.get("path", "")], kwargs)
    if event_type == "input.key":
        key = data.get("key", data.get("resolved_key", ""))
        method = "key_down" if bool(data.get("pressed", True)) else "key_up"
        return f"godot.{method}({_py(key)}{_modifier_kwargs(data)})"
    if event_type == "input.text":
        return f"godot.input_text({_py(data.get('text', ''))})"
    if event_type == "input.action":
        return (
            f"godot.input_action({_py(data.get('action', ''))}, "
            f"{_py(bool(data.get('pressed', True)))}, {_py(data.get('strength', 1.0))})"
        )
    if event_type == "input.action.configure":
        kwargs = []
        if "deadzone" in data and data.get("deadzone") is not None:
            kwargs.append(("deadzone", data.get("deadzone")))
        if "events" in data and data.get("events") not in (None, []):
            kwargs.append(("events", data.get("events")))
        if bool(data.get("replace", data.get("replaced", False))):
            kwargs.append(("replace", True))
        if data.get("create", True) is False:
            kwargs.append(("create", False))
        return _call("godot.input_action_configure", [data.get("action", data.get("name", ""))], kwargs)
    if event_type == "input.action.erase":
        kwargs = []
        if "events" in data and data.get("events") not in (None, []):
            kwargs.append(("events", data.get("events")))
        if bool(data.get("events_only", data.get("clear_events", False))):
            kwargs.append(("events_only", True))
        return _call("godot.input_action_erase", [data.get("action", data.get("name", ""))], kwargs)
    if event_type == "input.joypad":
        return _joypad_line(data)
    if event_type == "input.mouse":
        return _mouse_line(data)
    if event_type == "input.touch":
        return _touch_line(data)
    if event_type == "viewport.set_size":
        size = _viewport_size(data)
        if size is None:
            return _unsupported_comment(event_type, data, detail="trace omits viewport size")
        return f"godot.set_viewport_size({_py(size[0])}, {_py(size[1])})"
    if event_type == "viewport.screenshot":
        return f"godot.screenshot({_py(data.get('path', 'screenshot.png'))})"
    if event_type == "fs.read_text":
        return f"godot.fs_read_text({_py(data.get('path', ''))})"
    if event_type == "fs.read_bytes":
        kwargs = []
        if data.get("max_bytes", 0) != 0:
            kwargs.append(("max_bytes", data.get("max_bytes")))
        return _call("godot.fs_read_bytes", [data.get("path", "")], kwargs)
    if event_type == "fs.write_text":
        return _unsupported_comment(event_type, data, detail="trace omits written text contents")
    if event_type == "fs.write_bytes":
        return _unsupported_comment(event_type, data, detail="trace omits written byte contents")
    if event_type == "fs.mkdir":
        return f"godot.fs_mkdir({_py(data.get('path', ''))})"
    if event_type == "fs.grep":
        kwargs = []
        for name, default in (
            ("case_sensitive", True),
            ("recursive", True),
            ("include_hidden", False),
            ("include_binary", False),
            ("name", ""),
            ("name_contains", ""),
            ("extension", ""),
            ("resource_type", ""),
            ("context_lines", 0),
            ("max_files", 500),
            ("max_results", 500),
            ("max_matches_per_file", 20),
        ):
            if name in data and data.get(name) != default:
                kwargs.append((name, data.get(name)))
        return _call("godot.fs_grep", [data.get("query", data.get("text", "")), data.get("path", "res://")], kwargs)
    if event_type == "fs.copy":
        return _call("godot.fs_copy", [data.get("source", data.get("from", "")), data.get("destination", data.get("to", ""))], _fs_relocate_kwargs(data))
    if event_type == "fs.move":
        return _call("godot.fs_move", [data.get("source", data.get("from", "")), data.get("destination", data.get("to", ""))], _fs_relocate_kwargs(data))
    if event_type == "fs.replace_text":
        kwargs = []
        if data.get("expected_replacements", 1) != 1:
            kwargs.append(("expected_replacements", data.get("expected_replacements")))
        if data.get("case_sensitive") is False:
            kwargs.append(("case_sensitive", False))
        if data.get("max_replacements", 0) != 0:
            kwargs.append(("max_replacements", data.get("max_replacements")))
        if bool(data.get("dry_run", False)):
            kwargs.append(("dry_run", True))
        if data.get("require_text_file") is False:
            kwargs.append(("require_text_file", False))
        if data.get("max_preview", 20) != 20:
            kwargs.append(("max_preview", data.get("max_preview")))
        return _call("godot.fs_replace_text", [data.get("path", ""), data.get("old_text", ""), data.get("new_text", "")], kwargs)
    if event_type == "fs.replace_text_many":
        kwargs = []
        for name, default in (
            ("expected_files", -1),
            ("expected_replacements", -1),
            ("case_sensitive", True),
            ("recursive", True),
            ("include_hidden", False),
            ("include_binary", False),
            ("name", ""),
            ("name_contains", ""),
            ("extension", ""),
            ("resource_type", ""),
            ("dry_run", True),
            ("max_files", 500),
            ("max_replacements_per_file", 100),
            ("max_total_replacements", 500),
            ("max_preview", 20),
        ):
            if data.get(name, default) != default:
                kwargs.append((name, data.get(name)))
        return _call(
            "godot.fs_replace_text_many",
            [data.get("old_text", ""), data.get("new_text", ""), data.get("path", "res://")],
            kwargs,
        )
    if event_type == "fs.delete":
        return f"godot.fs_delete({_py(data.get('path', ''))})"
    if event_type == "resource.files":
        kwargs = []
        for name, default in (
            ("path", "res://"),
            ("name", ""),
            ("name_contains", ""),
            ("resource_name", ""),
        ):
            if data.get(name, default) != default:
                kwargs.append((name, data.get(name)))
        class_filter = data.get("class_name", data.get("class", ""))
        if class_filter:
            kwargs.append(("class_name", class_filter))
        if data.get("max_results", 200) != 200:
            kwargs.append(("max_results", data.get("max_results")))
        if data.get("extensions") not in (None, ["tres", "res"]):
            kwargs.append(("extensions", data.get("extensions")))
        if data.get("include_dependencies") is False:
            kwargs.append(("include_dependencies", False))
        if data.get("include_properties") is True:
            kwargs.append(("include_properties", True))
        if data.get("recursive") is False:
            kwargs.append(("recursive", False))
        if data.get("include_hidden") is True:
            kwargs.append(("include_hidden", True))
        if data.get("max_scan_results") is not None:
            kwargs.append(("max_scan_results", data.get("max_scan_results")))
        return _call("godot.resource_files", [], kwargs)
    if event_type == "resource.file.describe":
        kwargs = []
        if data.get("include_properties") is False:
            kwargs.append(("include_properties", False))
        if data.get("include_resources") is False:
            kwargs.append(("include_resources", False))
        if data.get("include_dependencies") is False:
            kwargs.append(("include_dependencies", False))
        if data.get("include_source") is True:
            kwargs.append(("include_source", True))
        return _call("godot.resource_file_describe", [data.get("path", "")], kwargs)
    if event_type == "resource.save":
        kwargs = []
        if data.get("class", "Resource") != "Resource":
            kwargs.append(("class_name", data.get("class")))
        if data.get("properties"):
            kwargs.append(("properties", data.get("properties")))
        return _call("godot.resource_save", [data.get("path", "")], kwargs)
    if event_type == "resource.classes":
        kwargs = []
        for name, default in (
            ("base_class", "Resource"),
            ("name_contains", ""),
            ("max_results", 200),
        ):
            if data.get(name, default) != default:
                kwargs.append((name, data.get(name)))
        if data.get("include_abstract") is True:
            kwargs.append(("include_abstract", True))
        if data.get("include_disabled") is True:
            kwargs.append(("include_disabled", True))
        if data.get("include_property_counts") is False:
            kwargs.append(("include_property_counts", False))
        return _call("godot.resource_classes", [], kwargs)
    if event_type == "resource.class.describe":
        kwargs = []
        if data.get("storage_only") is True:
            kwargs.append(("storage_only", True))
        return _call("godot.resource_class_describe", [data.get("class", "Resource")], kwargs)
    if event_type == "resource.set_properties":
        kwargs = []
        if data.get("type_hint", ""):
            kwargs.append(("type_hint", data.get("type_hint")))
        if data.get("save") is False:
            kwargs.append(("save", False))
        if data.get("require_existing_properties") is False:
            kwargs.append(("require_existing_properties", False))
        if data.get("inspect") is True:
            kwargs.append(("inspect", True))
        return _call("godot.resource_set_properties", [data.get("path", ""), data.get("properties", {})], kwargs)
    if event_type == "resource.duplicate":
        kwargs = []
        if data.get("properties"):
            kwargs.append(("properties", data.get("properties")))
        if data.get("type_hint", ""):
            kwargs.append(("type_hint", data.get("type_hint")))
        if data.get("deep") is False:
            kwargs.append(("deep", False))
        if data.get("overwrite") is False:
            kwargs.append(("overwrite", False))
        if data.get("require_existing_properties") is False:
            kwargs.append(("require_existing_properties", False))
        if data.get("inspect") is True:
            kwargs.append(("inspect", True))
        return _call("godot.resource_duplicate", [data.get("source", ""), data.get("destination", "")], kwargs)
    if event_type == "resource.dependencies":
        return _call("godot.resource_dependencies", [data.get("path", "")])
    if event_type == "resource.references":
        kwargs = []
        for name, default in (
            ("uid", ""),
            ("search_path", "res://"),
            ("dependency_type", ""),
            ("resource_type", ""),
            ("max_results", 200),
        ):
            if data.get(name, default) != default:
                kwargs.append((name, data.get(name)))
        if data.get("exists") is not None:
            kwargs.append(("exists", data.get("exists")))
        if data.get("extensions") is not None:
            kwargs.append(("extensions", data.get("extensions")))
        if data.get("recursive") is False:
            kwargs.append(("recursive", False))
        if data.get("include_hidden") is True:
            kwargs.append(("include_hidden", True))
        if data.get("max_scan_results") is not None:
            kwargs.append(("max_scan_results", data.get("max_scan_results")))
        return _call("godot.resource_references", [data.get("path", data.get("target_path", ""))], kwargs)
    if event_type == "resource.move":
        kwargs = []
        for name, default in (
            ("update_references", True),
            ("dry_run", False),
            ("search_path", "res://"),
            ("recursive", True),
            ("include_hidden", False),
            ("overwrite", True),
            ("create_dirs", True),
            ("expected_reference_files", -1),
            ("expected_replacements", -1),
            ("max_reference_files", 200),
            ("max_replacements_per_file", 100),
            ("max_total_replacements", 500),
            ("max_preview", 20),
            ("allow_truncated", False),
            ("allow_scan_truncated", False),
            ("allow_unpatched", False),
        ):
            if data.get(name, default) != default:
                kwargs.append((name, data.get(name)))
        if data.get("extensions") is not None:
            kwargs.append(("extensions", data.get("extensions")))
        if data.get("max_scan_results") is not None:
            kwargs.append(("max_scan_results", data.get("max_scan_results")))
        return _call(
            "godot.resource_move",
            [data.get("source", data.get("from", data.get("path", ""))), data.get("destination", data.get("to", ""))],
            kwargs,
        )
    if event_type == "resource.imports":
        kwargs = []
        for name, default in (
            ("path", "res://"),
            ("name", ""),
            ("name_contains", ""),
            ("importer", ""),
            ("resource_type", ""),
            ("max_results", 200),
        ):
            if data.get(name, default) != default:
                kwargs.append((name, data.get(name)))
        if data.get("extensions") is not None:
            kwargs.append(("extensions", data.get("extensions")))
        for name in ("generated_files_ready", "imported", "ok"):
            if data.get(name) is not None:
                kwargs.append((name, data.get(name)))
        if data.get("include_missing_metadata") is False:
            kwargs.append(("include_missing_metadata", False))
        if data.get("recursive") is False:
            kwargs.append(("recursive", False))
        if data.get("include_hidden") is True:
            kwargs.append(("include_hidden", True))
        if data.get("max_scan_results") is not None:
            kwargs.append(("max_scan_results", data.get("max_scan_results")))
        return _call("godot.resource_imports", [], kwargs)
    if event_type == "resource.import_metadata":
        return _call("godot.resource_import_metadata", [data.get("path", "")])
    if event_type == "resource.reimport":
        kwargs = []
        if data.get("force") is True:
            kwargs.append(("force", True))
        return _call("godot.resource_reimport", [_single_path_or_list(data.get("paths", data.get("requested", [])))], kwargs)
    if event_type == "signal.watch":
        kwargs = []
        if data.get("once") is True:
            kwargs.append(("once", True))
        return "_signal_watch = " + _call("godot.signal_watch", [_node_path(data.get("path", data.get("selector", ""))), data.get("signal", "")], kwargs)
    if event_type == "signal.unwatch":
        return _call("godot.signal_unwatch", [data.get("watch_id", data.get("id", ""))])
    if event_type == "signal.event":
        kwargs = []
        if data.get("signal"):
            kwargs.append(("signal", data.get("signal")))
        if data.get("path"):
            kwargs.append(("path", data.get("path")))
        return _call("godot.wait_for_signal_event", [], kwargs)
    if event_type == "signal.connect":
        kwargs = [("method", data.get("method", ""))]
        if data.get("target"):
            kwargs.append(("target", _node_path(data.get("target"))))
        if data.get("flags") not in (None, 0):
            kwargs.append(("flags", data.get("flags")))
        return _call("godot.signal_connect", [_node_path(data.get("source", data.get("selector", ""))), data.get("signal", "")], kwargs)
    if event_type == "signal.disconnect":
        kwargs = [("method", data.get("method", ""))]
        if data.get("target"):
            kwargs.append(("target", _node_path(data.get("target"))))
        return _call("godot.signal_disconnect", [_node_path(data.get("source", data.get("selector", ""))), data.get("signal", "")], kwargs)
    if event_type == "project.set_setting":
        save = bool(data.get("save", data.get("saved", False)))
        kwargs = [] if not save else [("save", True)]
        return _call("godot.project_set_setting", [data.get("name", ""), data.get("value")], kwargs)
    if event_type == "project.summary":
        kwargs = []
        for name, default in (
            ("path", "res://"),
            ("max_results", 50),
            ("include_input_events", False),
            ("include_ui_actions", True),
            ("include_imports", True),
        ):
            if data.get(name, default) != default:
                kwargs.append((name, data.get(name)))
        return _call("godot.project_summary", [], kwargs)
    if event_type == "project.doctor":
        kwargs = []
        for name, default in (
            ("path", "res://"),
            ("max_results", 50),
            ("include_input_events", False),
            ("include_ui_actions", True),
            ("include_imports", True),
            ("include_protocol_methods", False),
        ):
            if data.get(name, default) != default:
                kwargs.append((name, data.get(name)))
        return _call("godot.project_doctor", [], kwargs)
    if event_type == "project.set_export_preset":
        kwargs = []
        for name, default in (
            ("index", None),
            ("export_path", ""),
            ("runnable", True),
            ("dedicated_server", False),
            ("custom_features", ""),
            ("export_filter", "all_resources"),
            ("include_filter", ""),
            ("exclude_filter", ""),
            ("encryption_include_filters", ""),
            ("encryption_exclude_filters", ""),
            ("encrypt_pck", False),
            ("encrypt_directory", False),
            ("script_export_mode", 2),
            ("options", {}),
            ("fields", {}),
            ("overwrite", True),
        ):
            if name in data and data.get(name) != default:
                kwargs.append((name, data.get(name)))
        return _call("godot.project_set_export_preset", [data.get("name", ""), data.get("platform", "")], kwargs)
    if event_type == "project.set_main_scene":
        kwargs = []
        if bool(data.get("save", data.get("saved", False))):
            kwargs.append(("save", True))
        if data.get("require_exists", True) is False:
            kwargs.append(("require_exists", False))
        return _call("godot.project_set_main_scene", [data.get("path", data.get("scene", ""))], kwargs)
    if event_type == "project.add_autoload":
        kwargs = []
        if data.get("singleton", True) is False:
            kwargs.append(("singleton", False))
        if bool(data.get("save", data.get("saved", False))):
            kwargs.append(("save", True))
        if data.get("overwrite", True) is False:
            kwargs.append(("overwrite", False))
        if data.get("require_exists", True) is False:
            kwargs.append(("require_exists", False))
        if data.get("order") is not None:
            kwargs.append(("order", data.get("order")))
        return _call("godot.project_add_autoload", [data.get("name", ""), data.get("path", "")], kwargs)
    if event_type == "project.remove_autoload":
        save = bool(data.get("save", data.get("saved", False)))
        kwargs = [] if not save else [("save", True)]
        return _call("godot.project_remove_autoload", [data.get("name", "")], kwargs)
    return None


def _paired_key_press(events: list[dict[str, Any]], index: int) -> str | None:
    first = events[index]
    if not bool(_event_data(first).get("pressed", True)):
        return None
    if index + 1 >= len(events):
        return None
    second = events[index + 1]
    if second.get("type") != "input.key":
        return None
    first_data = _event_data(first)
    second_data = _event_data(second)
    if bool(second_data.get("pressed", True)):
        return None
    if first_data.get("key") != second_data.get("key"):
        return None
    if first_data.get("modifiers", {}) != second_data.get("modifiers", {}):
        return None
    return f"godot.press({_py(first_data.get('key', first_data.get('resolved_key', '')))}{_modifier_kwargs(first_data)})"


def _joypad_line(data: dict[str, Any]) -> str:
    joypad_type = str(data.get("type", "button"))
    if joypad_type == "axis":
        return f"godot.joypad_axis({_py(data.get('axis', data.get('axis_index', 0)))}, {_py(data.get('value', 0.0))}, device={_py(data.get('device', 0))})"
    button = data.get("button", data.get("button_index", 0))
    if bool(data.get("pressed", True)):
        pressure = data.get("pressure")
        pressure_arg = "" if pressure in (None, 1, 1.0) else f", pressure={_py(pressure)}"
        return f"godot.joypad_button_down({_py(button)}{pressure_arg}, device={_py(data.get('device', 0))})"
    return f"godot.joypad_button_up({_py(button)}, device={_py(data.get('device', 0))})"


def _mouse_line(data: dict[str, Any]) -> str:
    x = data.get("x", 0.0)
    y = data.get("y", 0.0)
    mouse_type = str(data.get("type", "button"))
    if mouse_type == "move":
        button_mask = data.get("button_mask", 0)
        suffix = "" if not button_mask else f", button_mask={_py(button_mask)}"
        return f"godot.mouse_move({_py(x)}, {_py(y)}{suffix})"
    if mouse_type == "down":
        return f"godot.mouse_down({_py(x)}, {_py(y)}, button={_py(data.get('button', 1))})"
    if mouse_type == "up":
        return f"godot.mouse_up({_py(x)}, {_py(y)}, button={_py(data.get('button', 1))})"
    if mouse_type == "click":
        return f"godot.mouse_click({_py(x)}, {_py(y)}, button={_py(data.get('button', 1))})"
    if mouse_type == "wheel":
        return f"godot.mouse_wheel({_py(x)}, {_py(y)}, delta_x={_py(data.get('delta_x', 0.0))}, delta_y={_py(data.get('delta_y', 0.0))})"
    return f"godot.input_mouse({_py(x)}, {_py(y)}, type={_py(mouse_type)})"


def _touch_line(data: dict[str, Any]) -> str:
    x = data.get("x", 0.0)
    y = data.get("y", 0.0)
    index = data.get("index", 0)
    touch_type = str(data.get("type", "tap"))
    if touch_type == "tap":
        return f"godot.tap({_py(x)}, {_py(y)}, index={_py(index)})"
    if touch_type == "down":
        return f"godot.touch_down({_py(x)}, {_py(y)}, index={_py(index)})"
    if touch_type == "up":
        return f"godot.touch_up({_py(x)}, {_py(y)}, index={_py(index)})"
    if touch_type in {"drag", "move"}:
        return f"godot.touch_move({_py(x)}, {_py(y)}, index={_py(index)})"
    return f"godot.input_touch({_py(x)}, {_py(y)}, type={_py(touch_type)}, index={_py(index)})"


def _vector2_components(value: Any, *, fallback_x: Any = 0.0, fallback_y: Any = 0.0) -> tuple[Any, Any]:
    if isinstance(value, dict):
        return value.get("x", fallback_x), value.get("y", fallback_y)
    if isinstance(value, (list, tuple)) and len(value) >= 2:
        return value[0], value[1]
    return fallback_x, fallback_y


def _vector3_components(
    value: Any,
    *,
    fallback_x: Any = 0.0,
    fallback_y: Any = 0.0,
    fallback_z: Any = 0.0,
) -> tuple[Any, Any, Any]:
    if isinstance(value, dict):
        return value.get("x", fallback_x), value.get("y", fallback_y), value.get("z", fallback_z)
    if isinstance(value, (list, tuple)) and len(value) >= 3:
        return value[0], value[1], value[2]
    return fallback_x, fallback_y, fallback_z


def _physics_query_kwargs(
    data: dict[str, Any],
    *,
    dimensions: int,
    include_max_results: bool = False,
) -> list[tuple[str, Any]]:
    kwargs = []
    if data.get("collision_mask") is not None:
        kwargs.append(("collision_mask", data.get("collision_mask")))
    if data.get("collide_with_bodies") is False:
        kwargs.append(("collide_with_bodies", False))
    if data.get("collide_with_areas") is False:
        kwargs.append(("collide_with_areas", False))
    if include_max_results and data.get("max_results", 32) != 32:
        kwargs.append(("max_results", data.get("max_results")))
    return kwargs


def _camera3d_kwargs(data: dict[str, Any]) -> list[tuple[str, Any]]:
    kwargs = []
    camera = _node_path(data.get("camera"))
    if camera:
        kwargs.append(("camera", camera))
    if data.get("root") not in (None, "", "edited", "scene"):
        kwargs.append(("root", data.get("root")))
    if data.get("max_distance", 1000.0) != 1000.0:
        kwargs.append(("max_distance", data.get("max_distance")))
    return kwargs


def _viewport_size(data: dict[str, Any]) -> tuple[Any, Any] | None:
    if data.get("width") is not None and data.get("height") is not None:
        return data.get("width"), data.get("height")
    for outer_name in ("current", "viewport", "info"):
        outer = data.get(outer_name)
        if isinstance(outer, dict):
            for size_name in ("window_size", "size", "visible_rect"):
                size = outer.get(size_name)
                if isinstance(size, dict) and size.get("width") is not None and size.get("height") is not None:
                    return size.get("width"), size.get("height")
    return None


def _fs_relocate_kwargs(data: dict[str, Any]) -> list[tuple[str, Any]]:
    kwargs = []
    if data.get("overwrite") is False:
        kwargs.append(("overwrite", False))
    if data.get("create_dirs") is False:
        kwargs.append(("create_dirs", False))
    return kwargs


def _single_path_or_list(value: Any) -> Any:
    if isinstance(value, list) and len(value) == 1:
        return value[0]
    return value


def _node_path(value: Any) -> Any:
    if isinstance(value, dict):
        return value.get("path", value)
    return value


def _call(name: str, args: list[Any], kwargs: list[tuple[str, Any]] | None = None) -> str:
    parts = [_py(arg) for arg in args]
    parts.extend(f"{key}={_py(value)}" for key, value in (kwargs or []))
    return f"{name}({', '.join(parts)})"


def _locator(data: dict[str, Any]) -> str:
    return f"godot.locator({_py(data.get('path', data.get('selector', '')))})"


def _locator_for_selector(selector: Any, root: Any = None) -> str:
    root_arg = "" if root in (None, "", "edited", "scene") else f", root={_py(root)}"
    return f"godot.locator({_py(selector)}{root_arg})"


def _node_selector(data: dict[str, Any]) -> Any:
    return data.get("path", data.get("selector", data.get("node", "")))


def _is_default_root(root: Any) -> bool:
    return root in (None, "", "edited", "scene")


def _root_kwargs(data: dict[str, Any]) -> list[tuple[str, Any]]:
    root = data.get("root")
    return [] if _is_default_root(root) else [("root", root)]


def _optional_selector_args(data: dict[str, Any]) -> list[Any]:
    selector = data.get("selector")
    return [] if selector is None else [selector]


def _editor_history_kwargs(data: dict[str, Any]) -> list[tuple[str, Any]]:
    kwargs = _root_kwargs(data)
    if data.get("history_id") not in (None, 0):
        kwargs.append(("history_id", data.get("history_id")))
    return kwargs


def _editor_selection_selectors(data: dict[str, Any]) -> Any:
    selectors = data.get("selectors")
    if isinstance(selectors, list) and selectors:
        return selectors[0] if len(selectors) == 1 else selectors
    selector = data.get("selector")
    if selector is not None:
        return selector
    nodes = data.get("nodes")
    if isinstance(nodes, list):
        paths = [node.get("path") for node in nodes if isinstance(node, dict) and node.get("path")]
        if paths:
            return paths[0] if len(paths) == 1 else paths
    return data.get("path", "")


def _editor_target_call(data: dict[str, Any]) -> tuple[list[Any], list[tuple[str, Any]]]:
    args: list[Any] = []
    kwargs: list[tuple[str, Any]] = []
    selector = data.get("selector")
    if selector is not None:
        args.append(selector)
    elif data.get("path"):
        kwargs.append(("path", data.get("path")))
    elif data.get("resource_path"):
        kwargs.append(("resource_path", data.get("resource_path")))
    else:
        target = data.get("target")
        if isinstance(target, dict) and target.get("path"):
            path = target.get("path")
            if isinstance(path, str) and path.startswith("res://"):
                kwargs.append(("resource_path", path))
            else:
                kwargs.append(("path", path))
    kwargs.extend(_root_kwargs(data))
    return args, kwargs


def _editor_inspector_mutation_kwargs(data: dict[str, Any]) -> list[tuple[str, Any]]:
    kwargs: list[tuple[str, Any]] = []
    if data.get("save", data.get("saved", False)) is True:
        kwargs.append(("save", True))
    if data.get("inspect", True) is False:
        kwargs.append(("inspect", False))
    if data.get("inspector_only") is True:
        kwargs.append(("inspector_only", True))
    return kwargs


def _undo_kwargs(data: dict[str, Any]) -> list[tuple[str, Any]]:
    kwargs: list[tuple[str, Any]] = []
    if data.get("undo") is False:
        kwargs.append(("undo", False))
    if data.get("undo_action"):
        kwargs.append(("undo_action", data.get("undo_action")))
    return kwargs


def _kwargs_suffix(kwargs: list[tuple[str, Any]]) -> str:
    if not kwargs:
        return ""
    return ", " + ", ".join(f"{key}={_py(value)}" for key, value in kwargs)


def _select_option_arg(data: dict[str, Any]) -> Any:
    selected = data.get("selected")
    if isinstance(selected, dict):
        text = selected.get("text")
        if text:
            return text
        if selected.get("id") is not None:
            return {"id": selected["id"]}
        if selected.get("index") is not None:
            return {"index": selected["index"]}
    return data.get("selected", data)


def _select_tab_arg(data: dict[str, Any]) -> Any:
    selected = data.get("selected")
    if isinstance(selected, dict):
        if selected.get("metadata"):
            return {"metadata": selected["metadata"]}
        for key in ("title", "text"):
            if selected.get(key):
                return selected[key]
        if selected.get("index") is not None:
            return {"index": selected["index"]}
    return data.get("selected", data)


def _select_item_arg(data: dict[str, Any]) -> Any:
    selected = data.get("selected")
    if isinstance(selected, dict):
        if selected.get("metadata"):
            return {"metadata": selected["metadata"]}
        if selected.get("id") is not None:
            return {"id": selected["id"]}
        if selected.get("text"):
            return selected["text"]
        if selected.get("index") is not None:
            return {"index": selected["index"]}
    return data.get("selected", data)


def _select_list_arg(data: dict[str, Any]) -> Any:
    selected = data.get("selected")
    if not isinstance(selected, dict):
        return selected
    items = selected.get("items")
    if isinstance(items, list) and items:
        args = [_select_list_item_arg(item) for item in items if isinstance(item, dict)]
        return args[0] if len(args) == 1 else args
    if selected.get("value") is not None:
        return selected["value"]
    return selected


def _select_list_item_arg(item: dict[str, Any]) -> Any:
    if item.get("metadata"):
        return {"metadata": item["metadata"]}
    if item.get("text"):
        return item["text"]
    if item.get("index") is not None:
        return {"index": item["index"]}
    return item


def _select_tree_arg(data: dict[str, Any]) -> Any:
    selected = data.get("selected")
    if not isinstance(selected, dict):
        return selected
    items = selected.get("items")
    if isinstance(items, list) and items:
        args = [_select_tree_item_arg(item) for item in items if isinstance(item, dict)]
        return args[0] if len(args) == 1 else args
    if selected.get("value") is not None:
        return selected["value"]
    return selected


def _select_tree_item_arg(item: dict[str, Any]) -> Any:
    output: dict[str, Any] = {}
    if item.get("path"):
        output["path"] = item["path"]
    elif item.get("metadata"):
        output["metadata"] = item["metadata"]
    elif item.get("text"):
        output["text"] = item["text"]
    elif item.get("index_path"):
        output["index_path"] = item["index_path"]
    elif item.get("index") is not None:
        output["index"] = item["index"]
    if item.get("column") not in (None, 0):
        output["column"] = item["column"]
    return output or item


def _selected_item_checked(data: dict[str, Any]) -> bool | None:
    selected = data.get("selected")
    if not isinstance(selected, dict):
        return None
    if not bool(selected.get("checkable")):
        return None
    return bool(selected.get("checked"))


def _modifier_kwargs(data: dict[str, Any]) -> str:
    key = str(data.get("key", ""))
    if "+" in key:
        return ""
    modifiers = data.get("modifiers", {})
    if not isinstance(modifiers, dict):
        return ""
    parts = []
    for name in ("shift", "ctrl", "alt", "meta"):
        if bool(modifiers.get(name)):
            parts.append(f"{name}=True")
    return "" if not parts else ", " + ", ".join(parts)


def _event_data(event: dict[str, Any]) -> dict[str, Any]:
    data = event.get("data", {})
    return data if isinstance(data, dict) else {}


def _unsupported_comment(event_type: str, data: dict[str, Any], *, detail: str = "") -> str:
    suffix = "" if not detail else f" ({detail})"
    return f"# Unsupported trace event {event_type}{suffix}: {_py(data)}"


def _safe_test_name(name: str) -> str:
    normalized = re.sub(r"\W+", "_", name.strip())
    normalized = normalized.strip("_") or "generated_trace"
    if not normalized.startswith("test_"):
        normalized = f"test_{normalized}"
    if normalized[0].isdigit():
        normalized = f"test_{normalized}"
    return normalized


def _py(value: Any) -> str:
    return pformat(value, width=1000, compact=True, sort_dicts=True)
